spring.main.allow-bean-definition-overriding: true

resilience4j.circuitbreaker:
  configs:
    default:
      failureRateThreshold: 50 #??? ??? ?? ??
      slowCallRateThreshold: 100 #??? ??? ?? ?? ??(??: slowCallDUrationThreshold)
      slowCallDurationThreshold: 60000 #[ms]
      permittedNumberOfCallsInHalfOpenState: 4 #??? half-open ??? ?, ???? ??? ??
      maxWaitDurationInHalfOpenState: 1000 #??? half-open ??? ?, ???? ??? ?? ???? ??
      slidingWindowType: COUNT_BASED #???? ??? ???? ????, ???? ? ??
      slidingWindowSize: 10
      minimumNumberOfCalls: 5 #????? ???? ??? ??? ?? ?? ?
      waitDurationInOpenState: 10000 #[ms] open -> half-open?? ???? ? ???? ??
  instances:
    test:
      baseConfig: default

